### ISSUE TITLE
[BUG] resetserver is not available to OP players after permadeath is undone

### ISSUE THREAD

**Issue by drewburr** [Chryscorelab/HardcoreLife#14]
**Describe the bug**
When global_lives is true and the server experiences permadeath, the `/resetserver` command is no longer available to OP users.

**To Reproduce**
Be OP
Set lives to 1 with global_lives = true
Have a player die, causing permadeath
Set lives to 1
The /resetserver command will no longer be permitted to OP players

**Expected behavior**
The /resetserver should remain available to OP players

**Screenshots**
N/A

**Server (please complete the following information):**
 - HardcoreLife version 
2.1.1 
 - PaperMC version
paper-1.17.1-266
 - Attach available server log files
Not needed

**Additional context**
N/A

**Comment by DaFray31** [comment]
This is done ? because i tried to reproduce, but seems, corrected or false bug ?
