### ISSUE TITLE
[Feature] Gamemode 2 (adventure mode) on death (no remaining lives)

### ISSUE THREAD

**Issue by NoahThatsWack** [Chryscorelab/HardcoreLife#21]
**Is your feature request related to a problem? Please describe.**
Maybe 1.18 broke the perma-death feature, but it would be cool to see an option to force users into adventure mode once they run out of lives.

**Describe the solution you'd like**
On death (no remaining lives) the user would be put into adventure mode (gamemode 2) instead of spectator, or no death movement.

Running HardcoreLife v2.2.0

Thank you for the plugin!

**Comment by drewburr** [comment]
Thanks for submitting this, I like the idea! We could probably add a `permadeath_gamemode` config to `config.yaml` to support this feature. We would default it to `spectator` or similar to keep the default plugin behavior the same, but supports other gamemodes if you'd like to change it.

I'll need to think about how to handle assigning specific gamemodes. I guess it wouldn't make sense to allow Creative or Survival, but you never know what the use-case might be.

**Comment by NoahThatsWack** [comment]
That would be awesome! I do however have a question about a bug i keep running into. Whenever a player dies the server has an error passing the PlayerDeathEvent to the plugin. I have been trying to fix it all day to no luck :/ please help!

**Comment by DaFray31** [comment]
@NoahThatsWack 
I notice you use Spigot and not Paper, we developed HardcoreLife on Paper, not spigot. 
We can't guarantee that it works on spigot. 
Also, we haven't worked on the 1.18 transition yet, we are waiting for Paper to be stable.

**Comment by drewburr** [comment]
I've opened #22 to track our upgrade effort
