### ISSUE TITLE
[Feature] Update to 1.18

### ISSUE THREAD

**Issue by drewburr** [Chryscorelab/HardcoreLife#22]
Opening this up to start the discussion of updating this plugin to 1.18. I'd prefer to wait until PaperMC stabilizes, but it's probably not going to hurt to get a head start on this.

[1.18.1 branch](https://github.com/Chryscorelab/HardcoreLife/tree/update-1.18.1)
- [x] Port to Java 17 LTS

- [x] Fixs all bugs :)
- [x] Fix #23 
- [x] Added #16 
- [x] Added #21

**Comment by DaFray31** [comment]
I have created a branch named update-1.18.1 !
