### ISSUE TITLE
[BUG] No movement on player respawn.

### ISSUE THREAD

**Issue by NoahThatsWack** [Chryscorelab/HardcoreLife#23]
**Describe the bug**
When a player has more than 1 life (individually), the player will be frozen on respawn. No matter how many lives are left, as long as it does not fall to 0. However the player can move freely while jumping.

But, if the players life falls to 0, and is set back to 1, the player can freely move again.

**To Reproduce**

1. Config.yml settings:
```
starting_lives: 1           # Number of lives with which the players or server will start
global_lives: false          # true : Players will share lives with the server | false : Players will have their own lives
#death_movement: false       # Allow movement after hitting permadeath. If unset, defaults to the value of global_lives
natural_regeneration: true  # Enable or disable natural regeneration for all worlds. For the most hardcore experience, set this to 'false'
server_life_scaling: 0      # The number of lives to add when a new player joins. Supports decimal values. Requires global_lives: true
language: en_EN             # For changing the language of the plugin - NOT FULLY SUPPORTED
```

2. Set the players lives to 2, so the player can respawn.
3. Let the player die, and respawn. The player should now have 1 remaining life.
4. After respawning the player freezes.

**Expected behavior**
If the player has 2 lives, dies, and respawns. The player is frozen until completely running out of lives, and then respawning. The player however should be able to freely move until 0 lives.

**Server (please complete the following information):**

- HardcoreLife version 2.2.0
- PaperMC version: Paper version git-Paper-66 (MC: 1.18) (Implementing API version 1.18-R0.1-SNAPSHOT) (Git: dce79f3)

**Additional context**
Hardcore=false

Thank you for this awesome plugin. Looking forward to the new update!

**Comment by DaFray31** [comment]
Hello,
You use, Paper 1.18, but we don't support 1.18 yet. Your report will not be taken.
Thanks for your comprehension.
You can follow the update to the 1.18 here #22 (We are waiting for more stability in 1.18.1)

Regards,

**Comment by DaFray31** [comment]
Ok, seems i have fix, but that bug is strange. Should more investigation about my fix.
(Because, this should impact others versions)

**Comment by NoahThatsWack** [comment]
> Ok, seems i have fix, but that bug is strange. Should more investigation about my fix. (Because, this should impact others versions)

Idk if this breaks any other versions but taking the playerspeed code and nestling it inside the remaining lives code seemed to fix it.


Edited code;
`            if (remainingLives == 0) {
                // handle player permadeath
                TextComponent component = Component.text("§f[§6Server§f]§c§l" + player.getName() + " §rhas run out of lives.");
                server.broadcast(component);
                player.setGameMode(GameMode.SPECTATOR);
                if (!touchy.deathMovementEnabled()) {
                    player.setFlySpeed(0);
                    player.setWalkSpeed(0);
                }
                // Revive the player. Allows teleport to work
                player.setHealth(20);
                player.teleport(deathLocation);
            }
        }
    }
}
`

Original code; 
`            if (remainingLives == 0) {
                // handle player permadeath
                TextComponent component = Component.text("§f[§6Server§f]§c§l" + player.getName() + " §rhas run out of lives.");
                server.broadcast(component);
                player.setGameMode(GameMode.SPECTATOR);
                // Revive the player. Allows teleport to work
                player.setHealth(20);
                player.teleport(deathLocation);
            }
        }
        // Prevent movement on death
        if (!touchy.deathMovementEnabled()) {
            player.setFlySpeed(0);
            player.setWalkSpeed(0);
        }
    }
}
`

This fixed my issue with players having more than 1 life, and respawning with no movement! Also, thank you for the amazing communication, yall are some awesome developers!

**Comment by DaFray31** [comment]
When i say, i have fixed, its because i have done the change, see here : b2e4a09a3e1059cd1269945dabc959a4d00ac6d4
All change, are not in the main branch, but int he [1.18.1 branch](https://github.com/Chryscorelab/HardcoreLife/tree/update-1.18.1)
