### ISSUE TITLE
Download plugin file from github

### ISSUE THREAD

**Issue by Adirman** [Chryscorelab/HardcoreLife#26]
I was able to fix an issue I had with this. How do i download the plugin as a jar directly from the repository?

**Comment by DaFray31** [comment]
I don't quite understand your request, you can download the stable versions of the plugin here :
https://github.com/Chryscorelab/HardcoreLife/releases

**Comment by DaFray31** [comment]
You can try the nightly build of 1.19 here : https://github.com/Chryscorelab/HardcoreLife/suites/7057168531/artifacts/278185962

**Comment by Smooktober** [comment]
Will that fix the no movement on death glitch?

**Comment by DaFray31** [comment]
yes

**Comment by Smooktober** [comment]
ok ty
